### ISSUE TITLE
updatemeshbatch() and drawstate Removed.

### ISSUE THREAD

**Issue by Doppp** [haxegon/plugin_imgui#20]
```
Gfx.updatemeshbatch();
Gfx.drawstate = Gfx.DRAWSTATE_IMAGE;
```
These [two lines](https://github.com/haxegon/plugin_imgui/blob/master/plugins/Gui.hx#L151-L152) don't work anymore because of this [commit](https://github.com/haxegon/haxegon/commit/7337bfc2b8d7dba8a937a2a98c400abe55a02485#diff-95f8fea8376b56b2b206fec74535df30).

**Comment by Doppp** [comment]
@randomnine FYI.

**Comment by TerryCavanagh** [comment]
Fixed! Thanks for the report! 👍
